on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_CSHARP: true
        DEFAULT_BRANCH: master
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}