on:
  push:
    tags:
      - '*'

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

name: Release NuGet Package
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: | 
        dotnet pack Hallo --configuration Release --no-build -o ./dist
        dotnet pack Hallo.AspNetCore --configuration Release --no-build -o ./dist
        dotnet pack Hallo.AspNetCore.Mvc --configuration Release --no-build -o ./dist
    - name: Publish
      working-directory: ./dist
      run: dotnet nuget push "*.nupkg" --source nuget.org --api-key $NUGET_API_KEY --skip-duplicate